apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gradia-guard
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - identity-broker-rbac.yaml
  - workloads.yaml
  - network-policies.yaml
  - validating-admission-policy.yaml
